### ISSUE TITLE
How to support RTL for the title bar

### ISSUE THREAD

**Issue by shouzhong** [RISCSoftware/CreateEmbedLangTransform#2]
Thank you for providing this tool to support multiple languages.
Do you know how to support RTL for the title bar? I tried adding `RightToLeft="yes" RightAligned="yes"` to the Dialog element, but it didn't work for me.

**Comment by shouzhong** [comment]
wix version is 5.0.2

**Comment by jmairboeck** [comment]
That is out of scope for this tool. This tool just merges finished installer packages for different languages together to get a single multilingual package. The actual individual localized packages must be created first.

For support for WiX itself you can ask in the [WiX toolset discussions](https://github.com/orgs/wixtoolset/discussions) or look at [FireGiant](https://www.firegiant.com/) for commercial support.
